sftn_test:
    resource: '@SftnTestBundle/Resources/config/routing.yml'
    prefix:   /
sftn_test:
    resource: "@SftnTestBundle/Controller/"
    type:     annotation
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
