sftn_test_homepage:
    path:   /
    defaults:  { _controller: "SftnTestBundle:Default:index" }
   
sftn_test_contact:
      path:  /contact
      defaults: { _controller: "SftnTestBundle:Contact:send" }  